### ISSUE TITLE
Support for a Pre-Loaded GroundRuleStore in Weight Learning

### ISSUE THREAD

**Issue by gfarnadi** [eriq-augustine/psl#110]
Right now, the weight learning base class (WeightLearningApplication) will check for latent variables and then run grounding.
After that it will call into the learning code that children are to implement.

However some special cases, specifically structure learning, we will need to run weight learning multiple times on similar models.
In this case, we want to be able to pass a pre-grounded GroundRuleStore (GRS) into weight learning.

This requires two main pieces:
 1. Passing a GroundRuleStore into weight learning constructors.
 2. Updating a GroundRuleStore with a new model.

Number 1 is pretty simple. It would be nice if we could move out some older/less used WL applications out to PSL Experimental.

Number 2 is not very hard. We will need to update the Grounding class to have some method like: update(Model, GroundRuleStore).
We could then look for any rules that are in the model, but not the GRS and ground them out. Then look for rules not in the model, but in the GRS and remove them.
This is also pretty interesting since we can leave the GroundAtom values at what they currently are after the last WL run as a hot start.

**Comment by eriq-augustine** [comment]
Complete in 0c2eafd4329741e28facf92c52821da191617855.
