### ISSUE TITLE
Different toString() formats for logical and arithmetic rules

### ISSUE THREAD

**Issue by eriq-augustine** [eriq-augustine/psl#13]
Lets make this consistent across all rules.

Examples:
(Input Rule String) -> (toString())
Logical:
"1: Single(A) & Double(A, B) >> Single(B) ^2" -> "{1.0} ( SINGLE(A) & DOUBLE(A, B) ) >> SINGLE(B) {squared}"

Arithmetic:
"1: Single(A) = 1 ^2" -> "1.0: 1.0 * SINGLE(A) = 1.0 ^2"

Notice the weights and squaring are represented differently.

**Comment by eriq-augustine** [comment]
More inconsistencies:
Unweighted Rules:
- Logical: Starts with "{constraint}"
- Arithmetic: Ends with "." (peroid)

Not Squared (but weighted):
- Logical: Ends with nothing.
- Arithmetic: Ends with "^1"

**Comment by eriq-augustine** [comment]
Added initial version in 8502f9fb691d2f81714dc6ce373da600b1c343b9.
I choose a consistent format just to start the discussion.

Weighted:
- Starts with "<weight>: "

Unweighted:
- Starts with "{constraint}: "
- Matches more closely with weights.

Not Squared:
- Ends with nothing

Squared:
- Ends with "{squared}"

**Comment by eriq-augustine** [comment]
Print out in parsable format.
Include a pretty print method.

For Squaring: nothing / ^2
Weights: Just colon

**Comment by stephenbach** [comment]
Also need to handle special predicates like NOTEQUAL, currently prints as #NOTEQUAL(A,B), should be A != B .
