### ISSUE TITLE
New Interface to Join Database and ReadonlyDatabase

### ISSUE THREAD

**Issue by eriq-augustine** [eriq-augustine/psl#152]
We need a new interface to join these two (ReadableDatabase maybe?).
This is because we have some classes like Queries which can be useful for both classes.

Once this is done we need to see were we can replace Database instances with this new interface (Queries is an obvious target).

**Comment by cfpryor** [comment]
Closed in cd379ae2529533d1cbbb8c5e80f097bb62ae0d19.
