### ISSUE TITLE
Rethink ReadOnlyDatabase

### ISSUE THREAD

**Issue by eriq-augustine** [eriq-augustine/psl#153]
The core concept is fine, but I am not happy with some of the deeper semantics.
Specifically in getAtoms() and executeQuery().
In these methods, exceptions are thrown if a non-closed predicate is accessed.
This is the semantic that I have issue with.

Should we just disallow accessing open predicates (as is the current behavior), or should we wrap RandomVariableAtoms (RVAs) in an immutable wrapper (say FixedRandomVariableAtom (which will throw an UnsupportedOperationException on setValue())?
In the second method, we could also convert it to an ObservedAtom (OA), but then we could not differentiate between a true OA and an RVA.

**Comment by cfpryor** [comment]
Closed in cd379ae2529533d1cbbb8c5e80f097bb62ae0d19.
