### ISSUE TITLE
Tests/CI for psl-examples

### ISSUE THREAD

**Issue by eriq-augustine** [eriq-augustine/psl#190]
We need some tests/CI that runs all examples for all the interfaces.
Since we have run scripts, it would really just need to locate all the run.sh files, go to that directory, run it, fail on a non-zero exit code.

We can use the same tactic that psl-utils/experimental uses for their CI (pull the dev PSL main repo and build locally).

**Comment by eriq-augustine** [comment]
We will probably also want to run them all under postgres so our CI doesn't take like 2 hours.

**Comment by shrestabs** [comment]
I will be working on this one.

**Comment by eriq-augustine** [comment]
CLI runs are done, but we are going to push back this issue until we have pull back the non-CLI usage in the psl examples.
