### ISSUE TITLE
Create Better Data for simple-acquaintances 

### ISSUE THREAD

**Issue by eriq-augustine** [eriq-augustine/psl#191]
The simple-acquaintances example has some hand-generated data and doesn't even get a good score.
We should make different data (keeping with the same rules) that actually scores well.

We can also include a data generator, but the data itself should still be present in the `data` directory without a need for fetching.
The data should also still be relatively small (a user should be able to see all the data in one screen).

**Comment by eriq-augustine** [comment]
Also include a weight learning dataset maybe.

**Comment by vihanggodbole** [comment]
I'm working on this one.

**Comment by eriq-augustine** [comment]
Complete in 0a8504fbb2bc9058f32e7052681c1f8aacec6759.
