### ISSUE TITLE
Make Drug-Drug Prediction into a PSL Example

### ISSUE THREAD

**Issue by eriq-augustine** [eriq-augustine/psl#192]
Take the experimental code (bitbucket.org/linqs/psl-drug-interaction-prediction.git) and put it into psl-examples format.
This means that the data will need to be structured and the model implemented in all the interfaces.

Once the code is implemented for a single interface and psl-examples conventions, implementing the other interfaces is fairly easy.
However, that first step of converting the experiment to a psl-example can be difficult.
Talk to @eriq-augustine about the tricks he uses.

**Comment by jting2** [comment]
I will be doing this one
