### ISSUE TITLE
Command line arguments support for existing psl-examples interfaces

### ISSUE THREAD

**Issue by shrestabs** [eriq-augustine/psl#199]
Currently while executing psl-examples the run.sh of all interfaces (expect CLI) does not take command line arguments as parameters for psl or logging. CLI recently supported this feature. [https://github.com/linqs/psl-examples/pull/5](url) . This issue is to track command line arguments support for the groovy, java and python interfaces of psl-examples.

**Comment by eriq-augustine** [comment]
More succinctly stated, we want all of our standard implementations to be able to take in command line arguments like the cli.

Note that in interfaces that are less structured that the cli (every other interface), there are two places that work must be done: the interface itself and the example/suggested usage of the interface 
The interface itself refers to the package in the psl core repo (e.g. psl-groovy). The example/usage refer to the implementations in psl-examples.
It is very important that the correct line is drawn between them.
