### ISSUE TITLE
Updating Dependencies

### ISSUE THREAD

**Issue by eriq-augustine** [eriq-augustine/psl#21]
2.0 release is the time to update dependencies and clean out our pom's.

At the absolute minimum, we should update H2 to fix: https://github.com/linqs/psl/wiki/Fixing-NegativeArraySizeException-in-H2

**Comment by puuj** [comment]
I agree in general. I believe Nikhil tried the latest stable H2 and still experienced that bug (or perhaps another issue?). We should check with him about what the status of that is.

**Comment by eriq-augustine** [comment]
Contacted Nikhil.
Closing for now, will reopen if Nikil confirms issue.
