### ISSUE TITLE
Implement non-symmetric operator in parser

### ISSUE THREAD

**Issue by stephenbach** [eriq-augustine/psl#28]
Need to change PSL.g4 antlr grammar. Something like
```
termOperator
	:	termEqual
	|	notEqual
        |       nonsymmetric
	;

termEqual
	:	EQUAL EQUAL
	;

notEqual
	:	NEGATION EQUAL
	;

nonsymmetric
        :       SYMBOL1 SYMBOL2
```

then add logic to visitAtom in ModelLoader.java.

Then put the correct symbol in Atom.toString()

**Comment by eriq-augustine** [comment]
Added in 88074397381657da782e1bcef36707dee1055429.
I used modulus for now since is is the most non-symmetric binary operator we have available.
