### ISSUE TITLE
Identifier for rules to allow for flexibility in choosing which subset of rules to model

### ISSUE THREAD

**Issue by dhawaljoh** [eriq-augustine/psl#38]
Allowing selection of rules based on identifiers will allow us not to have to segregate them into functions and call only the required functions.

**Comment by eriq-augustine** [comment]
I am going to close this one since the PSL interfaces and motifs have changed considerably since this was initially opened.
With the CLI and new interfaces, marking the rule sets consistently is more burdensome than just managing them externally.
