### ISSUE TITLE
Rule resolution not consistent

### ISSUE THREAD

**Issue by dhawaljoh** [eriq-augustine/psl#46]
Someone has reported that these two do not produce the same results:
`~(Rel(A) ^ Rel(B) ^ Sub(A,B))`
`Rel(A) ^ Rel(B) -> !Sub(A,B)`

**Comment by eriq-augustine** [comment]
Possibly have something to do with the broken DNF in #50.

**Comment by eriq-augustine** [comment]
Note that the first syntax was previously impossible in the parser (now possible).
So this must be in the Groovy syntax.

**Comment by eriq-augustine** [comment]
I was unable to determine the exact cause of this.
I suspected something with the old getDNF() and got the DNF for each in the old grounding (4edaaff):
```
( ~( SINGLE(A) ) | ~( SINGLE(B) ) | ~( SIM(A, B) ) )
( ( ~( SINGLE(A) ) | ~( SINGLE(B) ) ) | ~( SIM(A, B) ) )
```
easier to see version:
```
( !A | !B | !C )
( ( !A | !B ) | !C )
```

Looks like the old getDNF() was slightly inefficient and missed a flatten opportunity, but these are still logically equivalent.

**Comment by eriq-augustine** [comment]
Closing since investigation turned up nothing and #50 rewrote the DNF functionality.
