### ISSUE TITLE
Ground Logical Rules Starting Values

### ISSUE THREAD

**Issue by eriq-augustine** [eriq-augustine/psl#54]
Starting the open random variables at the extrema sometimes causes less "fighting" during optimization and the inferred values all come out very close to the extrama that they started at.

We need to ponder this a bit and decide if we actually do want to start optimization out in the worst case (these extreme values).
Maybe start at a random value (after we calculate worst case and leave out some groundings).

See AbstractLogicalRule.groundFormula().

**Comment by gfarnadi** [comment]
Generating random values given a certain distribution may help.
