### ISSUE TITLE
Max operator does not work on non-binary predicates

### ISSUE THREAD

**Issue by varunembar** [eriq-augustine/psl#62]
I wanted to use a rule of the form 
Pred(R,E+)/@MAX[E+]  = 1.
where I wanted to compute the max of a bunch groundings.

But it looks like @MAX is a binary operators .

**Comment by eriq-augustine** [comment]
We will not be able to have variable values in coefficients.

As for non-binary values, you can now chain coefficient functions together like:
`@max[@min[0, 2], 1]`
