### ISSUE TITLE
Ponder: Positive, Arbitrary Priors

### ISSUE THREAD

**Issue by eriq-augustine** [eriq-augustine/psl#81]
Negative Priors are easy: 1.0: ~Foo(A, B) ^2
(wlog wight and squaring)
They are saying: "Start with a negative belief that needs to be overcome".

Positive priors conceptually make sense: "Start with some default belief".
But, PSL does not explicitly support those.
Sometimes people will create an additional, observed predicate and use that to load the prior information into the true predicate we are inferring:
Bar(A, B) = 0.3 (for all values)
1.0: Bar(A, B) -> Foo(A, B) ^2

But what about using arithmetic rules to directly specify a prior?
Something like: 1.0: Foo(A, B) = 0.3 ^2

A very rough test with a logical and arithmetic negative prior optimized to the same thing.

I think this needs to be thought about more and experimented on.
If all goes well, details need to be added to the wiki.

**Comment by dhawaljoh** [comment]
What is wrong with:
xyz: Foo(A,B) ^2?

Start with prior xyz belief for predicate Foo?

**Comment by eriq-augustine** [comment]
Short answer is that PSL does not allow it.
`IllegalArgumentException: All Variables must be used at least once as an argument for a negative literal with a StandardPredicate` is thrown.

However, even if it was allowed, we also want to investigate arbitrary priors.
What you have there would drive Foo(A, B) specifically to 1.

I think there are a lot more subtle semantic things going around here.

**Comment by eriq-augustine** [comment]
Arithmetic rules are indeed the way to go:
```
1.0: Foo(A, B) = 0.3 ^2
```
