### ISSUE TITLE
Error creating metadata table

### ISSUE THREAD

**Issue by nkini** [eriq-augustine/psl#83]
"459  [main] ERROR org.linqs.psl.database.rdbms.RDBMSDataStoreMetadata  - Error creating metadata table: Table "RDBMSDATASTORE_METADATA" already exists; SQL statement:
CREATE TABLE rdbmsdatastore_metadata (namespace VARCHAR(20), keytype VARCHAR(20), key VARCHAR(255), value VARCHAR(255), PRIMARY KEY(namespace,keytype,key)) [42101-192]"

Possibly an issue, but I'm not sure what the desired behavior is in the following scenario.

Reproducing this issue:
Set clearDB to false in
H2DatabaseDriver(H2DatabaseDriver.Type dbType, String path, boolean clearDB)
while a database with the data loaded exists at the appropriate path (e.g. Paths.get(config.dbPath, ID))

Example:
ds = new RDBMSDataStore(new H2DatabaseDriver(Type.Disk, Paths.get(config.dbPath, ID).toString(), **false**), cb);

**Comment by eriq-augustine** [comment]
Note that this error is printed, but does not stop the actual run.

**Comment by eriq-augustine** [comment]
Fixed as of bcbf79ce0ff251ab24f4fc08e115dcc5ad4fbd17.
