### ISSUE TITLE
ADMM: Calculating Dual Incompatibility

### ISSUE THREAD

**Issue by eriq-augustine** [eriq-augustine/psl#94]
The process for calculating dual incompatibility seems a bit roundabout.
First all gloabl variables taking part in the term for a ground rule are set to the local values.
Then the incompatibility is calculated. 

I am a bit concerned that the global values are not set back to their original values.
Also, is there a more efficient way we could do it?

**Comment by gfarnadi** [comment]
The calculation is correct, so you don't need to worry about the global values.

**Comment by eriq-augustine** [comment]
Complete in 3c478ae99baab30788f99d4803350001b95108c2.
We now will make sure that the consensus values (and variable values) are the same at the end of the method.
